server:
  port: 8084

# Application Config
spring:
  application:
    name: API-GATEWAY
    


# API Gateway Config

  cloud:
    gateway:
      routes:
      
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**
      
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**
          

    
# Discovery Client Config
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
 
#Okta Config
okta:
  oauth2:
    issuer: https://dev-49865484.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa92xtcqiOR3vztX5d7
    client-secret: xH6XCA-qrJCs4XEg6FKtIdzSu_nnLfegiQOgM7PP
    scopes: openid, profile, email, offline_access

      
  

