server:
  port: 8081
  
# DB Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER-SERVICE

# Jpa Config
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
# importing ServiceRegistry Config from ConfigServer
  config:
    import: configserver:http://localhost:8085
    
        
# ServiceRegistryClient Config #commented since we are importing
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
    