server:
  port: 8083
  
#DB Config
spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

# Jpa Config
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
 
# Importing Service Registry Client Config from ConfigServer
  config:
    import: configserver:http://localhost:8085
  profiles:
    active:
    - default

      
#Okta Config
okta:
  oauth2:
    issuer: https://dev-49865484.okta.com/oauth2/default
    audience: api://default
    
# ServiceRegistry Client Config
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
    