server:
  port: 8083
  
#DB Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

# Jpa Config
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    